### ISSUE TITLE
Problem with hexamer

### ISSUE THREAD

**Issue by mmidhun97** [BartBruininks/mdvwhole#41]
Dear all,
Im using mdvwhole for removing pbc in hexamer. But in dimer its working fine. But in case of hexamer we can see its not working properly. Could ypu please recommend if i need to add any additional flag or something.
Im using the following command "mdvwhole -f your_gro.gro -x your_xtc.xtc -o whole.xtc"

Also im attaching the snapshot of the frame it causes the problem with pbc

![vmd](https://github.com/BartBruininks/mdvwhole/assets/78221153/87627f52-e029-4a87-8f0d-2f1cfd076d83)

With Regards,
Midhun
PhD student,
Institute of physics, PAN
Warsaw, poland

**Comment by BartBruininks** [comment]
Dear Midhun,

The problem in this case is that your aggregate is spanning the periodic
boundary (crossing it from one edge to the other in a connected manner).
This means that the object (the aggregate of hexamers) cannot be completed
without breaking some contacts. In short you can complete the molecules,
buy not the aggregate. It is intrinsically periodic.

Please feel free to ask more if this answer is unclear. However, I am on
holidays for the coming 10 days, so I will not be able to show you hands on
what I mean until I get back.

Cheers,

Bart

Op di 18 jul. 2023 14:30 schreef mmidhun97 ***@***.***>:

**Comment by mmidhun97** [comment]
Dear Bart,

I think its clear for me. I will contact you if i have any further doubts. Thank you for your instant reply. 

With Regards,
Midhun
